### ISSUE TITLE
Null check necessity when using Console.ReadLine

### ISSUE THREAD

**Issue by oSumAtrIX** [BlauFx/Filesharing#6]
Simply asserting for null check is not enough as an environment might not support stdin
https://github.com/BlauFx/Filesharing/blob/2d8123be2eebe7d701a7f500c9bd1a82de2d2594/src/Program.cs#L36

**Comment by BlauFx** [comment]
Just noticed https://github.com/BlauFx/Filesharing/commit/0bbb428d2b793459772ce22a279af23f5a2a6765 also fixes this case.
