### ISSUE TITLE
Simplify in range check

### ISSUE THREAD

**Issue by oSumAtrIX** [BlauFx/Filesharing#7]
Instead of this, a simple conditional check should be used
https://github.com/BlauFx/Filesharing/blob/2d8123be2eebe7d701a7f500c9bd1a82de2d2594/src/Program.cs#L36

**Comment by BlauFx** [comment]
Fixed in https://github.com/BlauFx/Filesharing/commit/0bbb428d2b793459772ce22a279af23f5a2a6765
